CREATE TABLE IF NOT EXISTS schemas (
    id SERIAL PRIMARY KEY,
    endpoint TEXT,
    schema JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS changes (
  id SERIAL PRIMARY KEY,
  endpoint TEXT,
  change TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
